config/routes.rb
Rsacfod::Application.routes.draw do
  root :to => 'fires#index'
  get '/fires/get_incident/:incident_id(.:format)' => 'fires#get_incident'
  get '/fires/search_by_name' => 'fires#search_by_name'
  get '/fires/search_by_year(.:format)' => 'fires#search_by_year'
  get 'fires/archive/(:today)' => 'fires#index'
  get 'fires/export_all' => 'fires#export_all'
  get 'fires/get_complexes' => 'fires#get_complexes'
  delete 'users/delete/:id' => 'users#delete'
  post 'users/destroy/:id' => 'users#destroy'
  get 'fires/import' => 'fires#import'
  post 'fires/upload' => 'fires#upload'
  post 'fires/:id/strategy' => 'fires#set_strategy'  
  post 'fires/:id/calculate_prediction' => 'fires#calculate_prediction'
  get '/advanced_search' => 'fires#advanced_search'
  get '/advanced_results(.:format)' => 'fires#advanced_results'
  post '/advanced_results(.:format)' => 'fires#advanced_results'
  get '/fires/delete/:id' => 'fires#delete'
  delete '/fires/destroy' => 'fires#destroy'
  post '/fires/set_status' => 'fires#set_status'  
  post 'fires/:id/mtbs_status' => 'fires#set_mtbs_status'
  post 'fires/:id/ravg_status' => 'fires#set_ravg_status'
  post 'fires/:id/baer_status' => 'fires#set_baer_status'
  post 'fires/:id/nps_status' => 'fires#set_nps_status'
  post 'fires/:id/misc_status' => 'fires#set_misc_status'

  get '/get_srcdbs' => 'fires#get_srcdbs'
  resources :fires
  get '/date_form' => 'fires#date_form'
  get '/search(.:format)/:incident_name' => 'fires#search'
  get '/search_by_name(.:format)/:incident_name' => 'fires#search_by_name'
  get '/search_by_mapping_id(.:format)/:mappingId' =>'fires#search_by_mapping_id'
  get '/search_by_dates(.:format)' => 'fires#search_by_dates'
  get '/search_by_pr(.:format)/:ignore_threshold/:pr' => 'fires#search_by_pr'
  get '/search_by_pr_year(.:format)/:ignore_threshold/:srcdb/:year/:pr' => 'fires#search_by_pr_year'
  resources :users
  get 'users/make_admin/:id' => 'users#make_admin'
  get '/login' => 'access#login', :as => 'login'
  get '/logout' => 'access#logout', :as => 'logout'
  get 'access/attempt_login' => 'access#attempt_login'
  get 'mappings/delete/:id' => 'mappings#delete'
  delete 'mappings/destroy/:id(.:format)' => 'mappings#destroy'
  get 'mappings/list/:id' => 'mappings#index'
  get 'mappings/all(.:format)' => 'mappings#all'
  get 'mappings/all_by_event(.:format)' => 'mappings#all_by_event'
  resources :mappings
  get '/save_scene' => 'scenes#save_scene'
  get '/list_scenes/:fire_id' => 'scenes#list_scenes'
  post '/save_mapping' => 'mappings#save_mapping'
  post '/save_burn_bndy' => 'mappings#save_burn_bndy'

  get '/imports' => 'imports#index'
  get '/imports/delete' => 'imports#delete'
  get '/imports/add_to_fod' => 'imports#add_to_fod'
  post '/imports/update_fod' => 'imports#update_fod'
  get '/imports/pick_incident' => 'imports#pick_incident'
  get '/imports/ingest' => 'imports#ingest'
  resources :imports
  post '/manifests/sync' => 'manifests#sync'
  get '/qachecks/get_check/:mapping_id(.:format)' => 'qachecks#get_check'
  post '/qachecks/save' => 'qachecks#save'
  post '/save_product' => 'products#save_product'
  match '/delete_products' => 'products#delete_products', via: [:post]
  match '/delete_product' => 'products#delete_product', via: [:post]
end

app/views/common/_confirmation.html.erb
<div class="modal-header">
  <a href="#" class="close">×</a>
  <h3>Confirm Delete</h3>
</div>
<div class="modal-body" id="confirm-body">
  <p>
    Are you sure you want to delete <em><%= @imagery_request.service_name %>?</em>
  </p>
</div>
<div class="modal-footer">
  <%= link_to 'Delete', {:controller => 'access', :action => 'destroy', :id => @imagery_request.id}, :class => 'btn primary' %>
  <a href="#" id="cancel" class="btn secondary">Cancel</a>
</div>

app/views/common/_flashes.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert alert-info">
    <i class="icon-info-sign icon-white"></i>
    <%= content_tag :span, flash[:notice] %>
    <a class="close" href="#">&times;</a>
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="alert alert-error">
    <i class="icon-exclamation-sign"></i>
    <%= content_tag :span, flash[:error] %>
    <a class="close" href="#">&times;</a>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert alert-success">
    <i class="icon-ok-sign icon-white"></i>
    <%= content_tag :span, flash[:alert] %>
    <a class="close" href="#">&times;</a>
  </div>
<% end %>

app/views/common/_topbar.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
        <%= image_tag('fire_bw.png', :id => 'logo') %>
          <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to('Event Tracker Database', {:controller => 'fires', :action => 'index'}, :class => 'brand') %>
          <div class="nav-collapse">
            <ul class="nav">
              <% if  session[:user_id] %>
              <li class="">
                <%= link_to('IRWIN', {:controller => 'imports', :action => 'index'}) %>
              </li>
              <% end %>
              <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">Queries <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to '30 Days', :controller => 'fires', :action => 'index', :days => '30' %>
                  </li>
                  <li>
                    <%= link_to '60 Days', :controller => 'fires', :action => 'index', :days => '60' %>
                  </li>
                  <li>
                    <%= link_to '180 Days', :controller => 'fires', :action => 'index', :days => '180' %>
                  </li>
                  <li>
                    <%= link_to 'Last Year', :controller => 'fires', :action => 'index', :days => '365' %>
                  </li>
                  <li class="divider"></li>
                  <li class="">
                    <%= link_to('Search by Dates', {:controller => 'fires', :action => 'date_form'}) %>
                  </li>
                  <li class="">
                    <%= link_to('Advanced Search', {:controller => 'fires', :action => 'advanced_search'}) %>
                  </li>
                </ul>
              </li>

              <form action="<%= url_for(:controller => 'fires', :action => 'search_by_name') %>" class="navbar-search pull-left">
                <input type="text" placeholder="Search" class="search-query span2" name="incident_name">
              </form>
            </ul>
            <ul class="nav pull-right">
              <% if session[:user_id] %>
                <% if session[:isadmin] == true %>
                  <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Admin Tasks <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to 'Administer Users', :controller => 'users', :action => 'index' %>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to 'Logout', logout_path %>
                      </li>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to 'Logout', :controller => 'access', :action => 'logout' %></li>
                <% end %>
              <% else %>
                  <li><%= link_to 'Login', :controller => 'access', :action => 'login' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/common/_userconfirmation.html.erb
<div class="modal-header">
  <a class="close" data-dismiss="modal">×</a>
  <h3>Confirm Delete</h3>
</div>
<div class="modal-body" id="confirm-body">
  <p>
    Are you sure you want to delete <em><%= @user.full_name %>?</em>
  </p>
</div>
<div class="modal-footer">
  <%= link_to 'Delete', user_path, :method => :delete, :class => 'btn btn-primary' %>
  <a href="#" class="btn" data-dismiss="modal">Cancel</a>
</div>